#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

source ~/.cache/wal/colors.sh # pywal scheme

CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               off
# turn off border shadows
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.15
yabai -m config window_animation_duration	 0.30
yabai -m config active_window_opacity 		 0.93
yabai -m config normal_window_opacity 		 0.85
# enable borders
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
# no blur
yabai -m config window_border_blur			 off
# insert color from pywal
yabai -m config insert_feedback_color        0xff$CINSE
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Sketchybar
yabai -m config external_bar				 all:40:0
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   6

# SIP Required
# More window config
yabai -m config window_border_radius		 13
yabai -m config window_border_hidpi			 on


# App Rules
yabai -m rule --add app="Google Chrome" opacity=1.0
yabai -m rule --add app="kitty" opacity=0.93
# yabai -m rule --add app="^(Google Chrome|Firefox)$" manage=off
yabai -m rule --add app="^(LuLu|System Settings|GeekTool)$" border=off
yabai -m rule --add app="MyWallpaper" manage=off border=off
yabai -m rule --add app="Live Wallpaper" manage=off
yabai -m rule --add app="Steam" manage=off
yabai -m rule --add app="Minecraft Education" manage=off
yabai -m rule --add app="^(play|Genshin Impact|Silicio|Steam|Godot)$" manage=off opacity=1.0 border=off
